apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-graviton
  labels:
    app: hello-graviton
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-graviton
  template:
    metadata:
      labels:
        app: hello-graviton
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        karpenter.sh/capacity-type: spot
      containers:
        - name: app
          image: public.ecr.aws/nginx/nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
